Курсовой проект вариант № 1. Кабаргин Николай.
Nikolas1055/Course-project pull request #1
Opened 2021-05-10 06:57 UTC by Nikolas1055

Рабочая версия проекта 1.0

2021-05-10 07:04 UTC, Nikolas1055 commented
@revers-back Первая версия проекта.

2021-05-12 18:07 UTC, Nikolas1055 commented
Админский логин и пароль - admin / admin
Для HR'ов два логина - hr1 / password и hr2 / password
Остальные сотрудники как гости

2021-05-13 14:11 UTC, revers-back requested changes
Нужно четко разбить приложение на Слои
Как минимум на 3 
доменная модель 
сервисы 
Отображение

Почитать про паттерн MVP тема по нему будет позже

Прикрутить UI swing или JavaFx

2021-05-13 14:11 UTC, revers-back commented on CourseProject.iml
> +<?xml version="1.0" encoding="UTF-8"?>
должно быть в .gitignore 
генерировать тут 
https://www.toptal.com/developers/gitignore

2021-05-13 14:11 UTC, revers-back commented on CourseProject.iml
> +</module>
папка out и build тоже должна быть в gitiginre

2021-05-13 14:11 UTC, revers-back commented on src/Main.java
> +public class Main {
Из названия класса не понятно чем занимается

2021-05-13 14:11 UTC, revers-back commented on src/Main.java
> +public class Main {
Это скорее MainView или MainUi

2021-05-13 14:11 UTC, revers-back commented on src/baseclasses/DataBase.java
> +public class DataBase implements Serializable {
лучше хранить в JSON и при помощи либы GSON или Jackson писать в файл как текст
проще отлаживать - меньше проблем при модификации структыры БД

2021-05-13 14:11 UTC, revers-back commented on src/baseclasses/Department.java
> +public class Department implements Serializable {
каждый класс должен иметь комментарий в javadoc + каждый публичный метод

2021-05-13 14:11 UTC, revers-back commented on src/baseclasses/Employee.java
> +    public Employee(String surname, String name, String patronymic, LocalDate birthDate,
каждый с новой сттроки

2021-05-13 14:11 UTC, revers-back commented on src/baseclasses/Gender.java
> +public enum Gender {
смешиваеться view и доменнаня модель

2021-05-13 14:11 UTC, revers-back commented on src/baseclasses/Role.java
> +public enum Role {
смешиваеться view и доменнаня модель

2021-05-13 14:11 UTC, revers-back commented on src/baseclasses/Role.java
> +public enum Role {
при локалицаии будут проблемы

2021-05-13 14:11 UTC, revers-back commented on src/officeclasses/HROffice.java
> +            } catch (IndexOutOfBoundsException e) {
дублируется постояно 
            try {
                return dataBase.getPosts().get(Service.selector() - 1);
            } catch (IndexOutOfBoundsException e) {
                Service.println("Такой должности в списке нет. Повторите выбор.");
            }

нужно подумать как избавиться

2021-05-13 14:11 UTC, revers-back commented on src/serviceclasses/Initialize.java
> +    public void employeeInit() {
если прикрутить в json будут отнсоительно легко через файл заполнять

2021-05-17 14:22 UTC, Nikolas1055 commented on CourseProject.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Исправлено.

2021-05-17 14:22 UTC, Nikolas1055 commented on CourseProject.iml
> +</module>
Исправлено.

2021-05-17 14:22 UTC, Nikolas1055 commented on src/Main.java
> +public class Main {
Исправлено.

2021-05-17 14:22 UTC, Nikolas1055 commented on src/baseclasses/Department.java
> +public class Department implements Serializable {
Исправлено.

2021-05-17 14:22 UTC, Nikolas1055 commented on src/baseclasses/Employee.java
> +    public Employee(String surname, String name, String patronymic, LocalDate birthDate,
Исправлено.

2021-05-17 14:23 UTC, Nikolas1055 commented on src/officeclasses/HROffice.java
> +            } catch (IndexOutOfBoundsException e) {
Исправлено.

2021-05-28 14:10 UTC, merged